name: 🚀 deploy to production

on:
  push:
    branches:
      - main
env:
  ENVIRONMENT: production

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      ENVIRONMENT: production
    secrets:
      FED_CLIENT_ID: ${{ secrets.FED_CLIENT_ID }}

  sentry-release:
    name: 🔖 Sentry release Front
    runs-on: decathlon
    timeout-minutes: 5
    needs: build
    steps:
      - name: 🧹 Clean
        uses: dktunited/.github/actions/cleaner@v0
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 📦 Download front artifact
        uses: actions/download-artifact@v4
        with:
          name: front
          path: dist
      - name: 📦 Download back artifact
        uses: actions/download-artifact@v4
        with:
          name: back
          path: back/lib
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: weparis
          SENTRY_PROJECT: my-game-mobile-v2
        with:
          environment: production
          sourcemaps: ./dist ./back/lib

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      PROJECT_ID: my-game-mobile
      ENVIRONMENT: production
    secrets:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

  deploy-decathlon:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      PROJECT_ID: mygame-mobile-kcz8
      ENVIRONMENT: production
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_DECATHLON }}
      GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

  test-e2e:
    name: 🤖 End-to-end tests
    runs-on: decathlon
    needs: deploy
    steps:
      - name: 🧹 Clean
        uses: dktunited/.github/actions/cleaner@v0
      - name: Checkout
        uses: actions/checkout@v4
      - name: 🤌 Install PNPM version from package.json packageManager
        uses: ./.github/actions/pnpm-install
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_BASE_URL: https://my-game.decathlonweparis.com
        with:
          working-directory: test-end-to-end
          install-command: pnpm install
          command: pnpm cypress run
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-snapshots
          path: test-end-to-end/cypress/screenshots

  test-e2e-decathlon:
    name: 🤖 End-to-end tests Decathlon
    runs-on: decathlon
    needs: deploy-decathlon
    steps:
      - name: 🧹 Clean
        uses: dktunited/.github/actions/cleaner@v0
      - name: Checkout
        uses: actions/checkout@v4
      - name: 🤌 Install PNPM version from package.json packageManager
        uses: ./.github/actions/pnpm-install
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_BASE_URL: https://mygame-mobile-kcz8.web.app
        with:
          working-directory: test-end-to-end
          install-command: pnpm install
          command: pnpm cypress run
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-snapshots
          path: test-end-to-end/cypress/screenshots
